import { useTranslation } from "react-i18next";

const countryOptions = () => {
  const { t } = useTranslation();

  return [
    { label: t("turkiyeMsgTxt"), value: "TR" },
    { label: t("abdMsgTxt"), value: "US" },
    { label: t("arnavutlukMsgTxt"), value: "AL" },
    { label: t("ermenistanMsgTxt"), value: "AM" },
    { label: t("avustralyaMsgTxt"), value: "AU" },
    { label: t("avusturyaMsgTxt"), value: "AT" },
    { label: t("azerbaycanMsgTxt"), value: "AZ" },
    { label: t("bahreynMsgTxt"), value: "BH" },
    { label: t("belcikaMsgTxt"), value: "BE" },
    { label: t("bosnaHersekMsgTxt"), value: "BA" },
    { label: t("bulgaristanMsgTxt"), value: "BG" },
    { label: t("kanadaMsgTxt"), value: "CA" },
    { label: t("cinMsgTxt"), value: "CN" },
    { label: t("hirvatistanMsgTxt"), value: "HR" },
    { label: t("kibrisMsgTxt"), value: "CY" },
    { label: t("cekCumhuriyetiMsgTxt"), value: "CZ" },
    { label: t("danimarkaMsgTxt"), value: "DK" },
    { label: t("misirMsgTxt"), value: "EG" },
    { label: t("estonyaMsgTxt"), value: "EE" },
    { label: t("finlandiyaMsgTxt"), value: "FI" },
    { label: t("fransaMsgTxt"), value: "FR" },
    { label: t("gurcistanMsgTxt"), value: "GE" },
    { label: t("almanyaMsgTxt"), value: "DE" },
    { label: t("yunanistanMsgTxt"), value: "GR" },
    { label: t("hongKongMsgTxt"), value: "HK" },
    { label: t("macaristanMsgTxt"), value: "HU" },
    { label: t("hindistanMsgTxt"), value: "IN" },
    { label: t("iranMsgTxt"), value: "IR" },
    { label: t("irakMsgTxt"), value: "IQ" },
    { label: t("irlandaMsgTxt"), value: "IE" },
    { label: t("italyaMsgTxt"), value: "IT" },
    { label: t("japonyaMsgTxt"), value: "JP" },
    { label: t("kazakistanMsgTxt"), value: "KZ" },
    { label: t("koreMsgTxt"), value: "KR" },
    { label: t("kuveytMsgTxt"), value: "KW" },
    { label: t("kirgizistanMsgTxt"), value: "KG" },
    { label: t("letonyaMsgTxt"), value: "LV" },
    { label: t("makedonyaMsgTxt"), value: "MK" },
    { label: t("maltaMsgTxt"), value: "MT" },
    { label: t("hollandaMsgTxt"), value: "NL" },
    { label: t("yeniZelandaMsgTxt"), value: "NZ" },
    { label: t("norvecMsgTxt"), value: "NO" },
    { label: t("polonyaMsgTxt"), value: "PL" },
    { label: t("portekizMsgTxt"), value: "PT" },
    { label: t("katarMsgTxt"), value: "QA" },
    { label: t("romanyaMsgTxt"), value: "RO" },
    { label: t("rusyaMsgTxt"), value: "RU" },
    { label: t("arabistanMsgTxt"), value: "SA" },
    { label: t("sirbistanKaradagMsgTxt"), value: "CS" },
    { label: t("ispanyaMsgTxt"), value: "ES" },
    { label: t("isvecMsgTxt"), value: "SE" },
    { label: t("isvicreMsgTxt"), value: "CH" },
    { label: t("tacikistanMsgTxt"), value: "TJ" },
    { label: t("taylandMsgTxt"), value: "TH" },
    { label: t("turkmenistanMsgTxt"), value: "TM" },
    { label: t("ukraynaMsgTxt"), value: "UA" },
    { label: t("birlesikArapMsgTxt"), value: "AE" },
    { label: t("birlesikKrallikMsgTxt"), value: "GB" },
    { label: t("ozbekistanMsgTxt"), value: "UZ" }
  ];
};

export default countryOptions; 